apiVersion: v1
kind: Service
metadata:
  name: zuzu-nestjs-service
spec:
  selector:
    app: zuzu-nestjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  
      nodePort: 3005
  type: LoadBalancer  